"""Shared limits — AWS Bedrock web crawler allows 300 req/min/host; we target 80%."""

AWS_CRAWL_MAX_REQUESTS_PER_MINUTE = 300
CRAWL_RATE_LIMIT_FRACTION = 0.8
CRAWL_REQUESTS_PER_SECOND = (AWS_CRAWL_MAX_REQUESTS_PER_MINUTE / 60.0) * CRAWL_RATE_LIMIT_FRACTION  # 4.0
